version: '3.3'

services:
  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry_data:/var/lib/registry
    restart: always

  registry-ui:
    image: atcol/docker-registry-ui
    ports:
      - 8080:8080
    environment:
      REG1: http://registry.local:5000/v2/
